// Generated by CoffeeScript 1.6.2
(function() {
  var SVG;

  SVG = (function() {
    function SVG() {}

    SVG.prototype.initialize = function(containerElement) {
      return this.containerElement = containerElement;
    };

    return SVG;

  })();

}).call(this);

/*
//@ sourceMappingURL=svg.map
*/
